# Use postgres/example user/password credentials
version: '3.7'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user_login
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef